apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- namespace.yml
- database.yml
- redis.yml
- volumes.yml
- deployment.yml
- service.yml
- ingress.yml
