apiVersion: apps/v1
kind: Deployment
metadata:
  name: markmine-backend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markmine-frontend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
