apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: markmine-dev
resources:
  - ../../base/markmine
  - namespace.yml
  - configmap.yml
  - sealed-secret.yml
patches:
  - path: ingress-patch.yml
