apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/markmine
  - configmap.yml
  - sealed-secret.yml
patches:
  - path: ingress-patch.yml
  - path: namespace-patch.yml
