apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: markmine-dev
resources:
  - ../../base/markmine
  - configmap.yml
  - sealed-secret.yml
  - ghcr-sealed-secret.yml
  - ingressroute.yml
patches:
  - path: ingress-patch.yml
  - target:
      kind: Deployment
      name: markmine-backend
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-secret
  - target:
      kind: Deployment
      name: markmine-frontend
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-secret
  - target:
      kind: Namespace
      name: markmine
    patch: |
      - op: replace
        path: /metadata/name
        value: markmine-dev
      - op: add
        path: /metadata/labels/environment
        value: development
