apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: markmine-dev
resources:
  - ../../base/markmine
  - configmap.yml
  - sealed-secret.yml
patches:
  - path: ingress-patch.yml
  - target:
      kind: Namespace
      name: markmine
    patch: |
      - op: replace
        path: /metadata/name
        value: markmine-dev
      - op: add
        path: /metadata/labels/environment
        value: development
