apiVersion: apps/v1
kind: Deployment
metadata:
  name: markmine-backend
  namespace: markmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markmine-backend
  template:
    metadata:
      labels:
        app: markmine-backend
        policy-type: app
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/leotsgo/markmine-backend:main-2a6c400-1770277963 # {"$imagepolicy": "flux-system:markmine-backend"}
          command: ["bun", "run", "migrate"]
          envFrom:
            - configMapRef:
                name: markmine-config
            - secretRef:
                name: markmine-secrets
        - name: seed
          image: ghcr.io/leotsgo/markmine-backend:main-2a6c400-1770277963 # {"$imagepolicy": "flux-system:markmine-backend"}
          command: ["bun", "run", "db:seed"]
          envFrom:
            - configMapRef:
                name: markmine-config
            - secretRef:
                name: markmine-secrets
      containers:
        - name: backend
          image: ghcr.io/leotsgo/markmine-backend:main-2a6c400-1770277963 # {"$imagepolicy": "flux-system:markmine-backend"}
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: markmine-config
            - secretRef:
                name: markmine-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markmine-frontend
  namespace: markmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markmine-frontend
  template:
    metadata:
      labels:
        app: markmine-frontend
        policy-type: app
    spec:
      containers:
        - name: frontend
          image: ghcr.io/leotsgo/markmine-frontend:main-2a6c400-1770277960 # {"$imagepolicy": "flux-system:markmine-frontend"}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: API_URL
              value: "http://markmine-backend:3000"
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
