apiVersion: v1
kind: Service
metadata:
  name: markmine-backend
  namespace: markmine
spec:
  selector:
    app: markmine-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: markmine-frontend
  namespace: markmine
spec:
  selector:
    app: markmine-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
